import { Geist, Geist_Mono } from "next/font/google";
import { auth } from "../lib/auth";
import { SessionProvider } from "../components/hooks/SessionProvider";
import NavBar from "../components/ui/NavBar";
import SideBar from "../components/ui/SideBar";
import InDevMode from "../components/ui/InDevMode"
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  console.log("From Root", session);
  return (
    <html lang="en">
      <body className="flex flex-col h-dvh antialiased p-4 ">
        <InDevMode devMode/>
        <SessionProvider value={session}>
          <NavBar />
          <div className="flex-1 grid grid-cols-[200px_1fr] gap-x-4 mt-4 overflow-hidden">
            <SideBar />
            <main className="bg-neutral-800 rounded-lg  overflow-auto">
              {children}
            </main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
